#define KANGLE               	1
#define KBEHAVIOR            	2
#define KCALCULATED          	3
#define KCAPACITANCE         	4
#define KCENTERCENTER        	5
#define KCENTERLEFT          	6
#define KCENTERRIGHT         	7
#define KCHARGE              	8
#define KCONDUCTANCE         	9
#define KCURRENT             	10
#define KDISTANCE            	11
#define KDOCUMENT            	12
#define KENERGY              	13
#define KEXTEND              	14
#define KFLUX                	15
#define KFREQUENCY           	16
#define KGENERIC             	17
#define KGRAPHIC             	18
#define KINDUCTANCE          	19
#define KINOUT               	20
#define KINPUT               	21
#define KLOGICMODEL          	22
#define KLOWERCENTER         	23
#define KLOWERLEFT           	24
#define KLOWERRIGHT          	25
#define KMASKLAYOUT          	26
#define KMASS                	27
#define KMEASURED            	28
#define KMX                  	29
#define KMXR90               	30
#define KMY                  	31
#define KMYR90               	32
#define KNETLIST             	33
#define KOUTPUT              	34
#define KPCBLAYOUT           	35
#define KPOWER               	36
#define KR0                  	37
#define KR180                	38
#define KR270                	39
#define KR90                 	40
#define KREQUIRED            	41
#define KRESISTANCE          	42
#define KRIPPER              	43
#define KROUND               	44
#define KSCHEMATIC           	45
#define KSTRANGER            	46
#define KSYMBOLIC            	47
#define KTEMPERATURE         	48
#define KTIE                 	49
#define KTIME                	50
#define KTRUNCATE            	51
#define KUPPERCENTER         	52
#define KUPPERLEFT           	53
#define KUPPERRIGHT          	54
#define KVOLTAGE             	55
#define Kabs                 	56
#define KacLoad              	57
#define Kactual              	58
#define Kafter               	59
#define Kand                 	60
#define Kannotate            	61
#define Kapply               	62
#define Karc                 	63
#define Karray               	64
#define KarrayMacro          	65
#define KarrayRelatedInfo    	66
#define KarraySite           	67
#define Kassign              	68
#define KatLeast             	69
#define KatMost              	70
#define Kauthor              	71
#define KbaseArray           	72
#define Kbecomes             	73
#define Kbetween             	74
#define Kblock               	75
#define Kboolean             	76
#define KbooleanDisplay      	77
#define KbooleanMap          	78
#define KborderPattern       	79
#define KborderWidth         	80
#define KboundingBox         	81
#define Kbuild               	82
#define Kceiling             	83
#define Kcell                	84
#define KcellRef             	85
#define KcellType            	86
#define Kchange              	87
#define Kcircle              	88
#define Kcollector           	89
#define Kcolor               	90
#define Kcomment             	91
#define KcommentGraphics     	92
#define Kcompound            	93
#define Kconcat              	94
#define KconnectLocation     	95
#define Kconstant            	96
#define Kconstraint          	97
#define Kcontents            	98
#define KcornerType          	99
#define Kcriticality         	100
#define KcurrentMap          	101
#define Kcurve               	102
#define Kcycle               	103
#define KdataOrigin          	104
#define KdcFaninLoad         	105
#define KdcFanoutLoad        	106
#define KdcMaxFanin          	107
#define KdcMaxFanout         	108
#define Kdelay               	109
#define Kdelta               	110
#define Kderivation          	111
#define Kdesign              	112
#define Kdesignator          	113
#define Kdifference          	114
#define Kdirection           	115
#define Kdisplay             	116
#define Kdivide              	117
#define Kdominates           	118
#define Kdot                 	119
#define Kduration            	120
#define Ke                   	121
#define Kedif                	122
#define KedifLevel           	123
#define KedifVersion         	124
#define Kelse                	125
#define KenclosureDistance   	126
#define KendType             	127
#define Kentry               	128
#define Kequal               	129
#define Kescape              	130
#define Kevent               	131
#define Kexactly             	132
#define Kexternal            	133
#define Kfabricate           	134
#define Kfalse               	135
#define Kfigure              	136
#define KfigureArea          	137
#define KfigureGroup         	138
#define KfigureGroupObject   	139
#define KfigureGroupOverride 	140
#define KfigureGroupRef      	141
#define KfigurePerimeter     	142
#define KfigureWidth         	143
#define KfillPattern         	144
#define Kfix                 	145
#define Kfloor               	146
#define Kfollow              	147
#define KforEach             	148
#define KforbiddenEvent      	149
#define Kformal              	150
#define KformalList          	151
#define Kgenerate            	152
#define KglobalPortRef       	153
#define KgreaterThan         	154
#define KgridMap             	155
#define Kif                  	156
#define Kignore              	157
#define KincludeFigureGroup  	158
#define Kincreasing          	159
#define Kinitial             	160
#define Kinstance            	161
#define KinstanceBackAnnotate	162
#define KinstanceGroup       	163
#define KinstanceMap         	164
#define KinstanceRef         	165
#define Kinteger             	166
#define KintegerDisplay      	167
#define KinterFigureGroupSpacing	168
#define Kinterface           	169
#define Kintersection        	170
#define KintraFigureGroupSpacing	171
#define Kinverse             	172
#define Kisolated            	173
#define Kiterate             	174
#define Kjoined              	175
#define Kjustify             	176
#define KkeywordAlias        	177
#define KkeywordDefine       	178
#define KkeywordDisplay      	179
#define KkeywordLevel        	180
#define KkeywordMap          	181
#define KkeywordParameters   	182
#define KlessThan            	183
#define Klibrary             	184
#define KlibraryRef          	185
#define KlistOfNets          	186
#define KlistOfPorts         	187
#define Kliteral             	188
#define KloadDelay           	189
#define KlogicAssign         	190
#define KlogicInput          	191
#define KlogicList           	192
#define KlogicMapInput       	193
#define KlogicMapOutput      	194
#define KlogicOneOf          	195
#define KlogicOutput         	196
#define KlogicPort           	197
#define KlogicRef            	198
#define KlogicValue          	199
#define KlogicWaveform       	200
#define Kmaintain            	201
#define Kmatch               	202
#define Kmax                 	203
#define Kmember              	204
#define KmiNoMax             	205
#define KmiNoMaxDisplay      	206
#define Kmin                 	207
#define Kmnm                 	208
#define Kmod                 	209
#define KmultipleValueSet    	210
#define KmustJoin            	211
#define Kname                	212
#define Knegate              	213
#define Knet                 	214
#define KnetBackAnnotate     	215
#define KnetBundle           	216
#define KnetDelay            	217
#define KnetGroup            	218
#define KnetMap              	219
#define KnetRef              	220
#define KnoChange            	221
#define KnonPermutable       	222
#define Knot                 	223
#define KnotAllowed          	224
#define KnotchSpacing        	225
#define Knumber              	226
#define KnumberDefinition    	227
#define KnumberDisplay       	228
#define KoffPageConnector    	229
#define KoffsetEvent         	230
#define KopenShape           	231
#define Koptional            	232
#define Kor                  	233
#define Korientation         	234
#define Korigin              	235
#define KoverhangDistance    	236
#define KoverlapDistance     	237
#define Koversize            	238
#define Kowner               	239
#define Kpage                	240
#define KpageSize            	241
#define Kparameter           	242
#define KparameterAssign     	243
#define KparameterDisplay    	244
#define Kpath                	245
#define KpathDelay           	246
#define KpathWidth           	247
#define Kpermutable          	248
#define KphysicalDesignRule  	249
#define Kplug                	250
#define Kpoint               	251
#define KpointDisplay        	252
#define KpointList           	253
#define KpointSubtract       	254
#define KpointSum            	255
#define Kpolygon             	256
#define Kport                	257
#define KportBackAnnotate    	258
#define KportBundle          	259
#define KportDelay           	260
#define KportGroup           	261
#define KportImplementation  	262
#define KportInstance        	263
#define KportList            	264
#define KportListAlias       	265
#define KportMap             	266
#define KportRef             	267
#define Kproduct             	268
#define Kprogram             	269
#define Kproperty            	270
#define KpropertyDisplay     	271
#define KprotectionFrame     	272
#define Kpt                  	273
#define KrangeVector         	274
#define Krectangle           	275
#define KrectangleSize       	276
#define Krename              	277
#define Kresolves            	278
#define Kscale               	279
#define KscaleX              	280
#define KscaleY              	281
#define Ksection             	282
#define Kshape               	283
#define Ksimulate            	284
#define KsimulationInfo      	285
#define KsingleValueSet      	286
#define Ksite                	287
#define Ksocket              	288
#define KsocketSet           	289
#define Kstatus              	290
#define Ksteady              	291
#define KstrictlyIncreasing  	292
#define Kstring              	293
#define KstringDisplay       	294
#define Kstrong              	295
#define Ksubtract            	296
#define Ksum                 	297
#define Ksymbol              	298
#define Ksymmetry            	299
#define Ktable               	300
#define KtableDefault        	301
#define Ktechnology          	302
#define KtextHeight          	303
#define Kthen                	304
#define KtimeInterval        	305
#define KtimeStamp           	306
#define Ktiming              	307
#define Ktransform           	308
#define Ktransition          	309
#define Ktrigger             	310
#define Ktrue                	311
#define Kunconstrained       	312
#define Kundefined           	313
#define Kunion               	314
#define Kunit                	315
#define Kunused              	316
#define KuserData            	317
#define Kvariable            	318
#define Kversion             	319
#define Kview                	320
#define KviewList            	321
#define KviewMap             	322
#define KviewRef             	323
#define KviewType            	324
#define Kvisible             	325
#define KvoltageMap          	326
#define KwaveValue           	327
#define Kweak                	328
#define KweakJoined          	329
#define Kwhen                	330
#define Kwhile               	331
#define Kwritten             	332
#define KxCoord              	333
#define Kxor                 	334
#define KyCoord              	335
#define NKEYWORDS  335
