#include <stdio.h>
#include "defines.h"
#include "types.h"
#include "keywords.h"

/*** IMPORTED *****/
extern PARSETREE *token;
extern char *keywords[];

/*extern int inputmask;*/
extern void add_token();

static int inputmask = (-1 & ~COMMENT & ~GRAPHIC);

/******** flags for context sensitive rules *********/
static int Fvref, Fassign;      /* to change 'IDENT' into 'VALUEREF' */
static int Fext, Fpage, Ftech, Fcont, Fintf;

/********** defines for parser **********/
#define RULE		static
#define IS		() {int b = TRUE;
#define ZERO(n)		int n = FALSE;
#define FORM(keydef)	if(token->type!=keydef) return(FALSE);\
			else add_token()
#define CONDFORM(k,msk) if(token->type!=k) return(FALSE);\
			if(inputmask&msk) return(match_anyitem(TRUE));\
			else add_token()
#define ONCE		; b =
#define REPEAT		; while (b && token->type != ENDLIST) b =
#define OPTIONAL	; if (b && token->type != ENDLIST) b |=
#define G1(guard,f)	(!guard&&(guard=f()))
#define MATCH(keydef)	((token->data.token==keywords[keydef])?\
			(add_token(), TRUE): FALSE)
#define ENDFORM		; return( match_endlist( b));}
#define END		; return( b);}
#define ANYTAIL		; return( match_tail(b));}
#define FLAG(f)		; f=TRUE
#define UNFLAG(f)	; f=FALSE

/*********************************************************************/
/*       Functions for each EDIF grammar rule                        */
/*********************************************************************/

Pabs IS FORM(Kabs)
ONCE PnumberValue()
ENDFORM PacLoad IS FORM(KacLoad)
ONCE PmiNoMaxValue() || PmiNoMaxDisplay()
ENDFORM Pactual IS FORM(Kactual)
ONCE PformalNameRef()
ENDFORM Pafter IS FORM(Kafter)
ONCE PmiNoMaxValue()
REPEAT PlogicAssign() || Pfollow() || Pmaintain() || Pcomment()
    || PuserData()
ENDFORM Pand IS FORM(Kand)
REPEAT PbooleanValue()
ENDFORM Pannotate IS FORM(Kannotate)
ONCE PstringValue() || PstringDisplay()
ENDFORM Papply IS FORM(Kapply)
ONCE Pcycle()
REPEAT PlogicInput() || PlogicOutput() || Pcomment() || PuserData()
ENDFORM Parc IS FORM(Karc)
ONCE PpointValue() && PpointValue() && PpointValue()
ENDFORM Passign IS FORM(Kassign) FLAG(Fassign)
ONCE PvalueNameRef() && PtypedValue() UNFLAG(Fassign)
ENDFORM Parray IS FORM(Karray)
ONCE PnameDef() && PintegerValue()
REPEAT PintegerValue()
ENDFORM ParrayMacro IS FORM(KarrayMacro)
ONCE Pplug()
ENDFORM ParrayRelatedInfo IS FORM(KarrayRelatedInfo)
ONCE ParrayMacro() || ParraySite() || PbaseArray()
REPEAT Pcomment() || PuserData()
ENDFORM ParraySite IS FORM(KarraySite)
ONCE Psocket()
ENDFORM PatLeast IS FORM(KatLeast)
ONCE PnumberValue()
ENDFORM PatMost IS FORM(KatMost)
ONCE PnumberValue()
ENDFORM Pauthor IS FORM(Kauthor)
ONCE PstringToken()
ENDFORM PbaseArray IS FORM(KbaseArray)
ENDFORM Pbecomes IS FORM(Kbecomes)
ONCE PlogicNameRef() || PlogicList() || PlogicOneOf()
ENDFORM Pbetween IS FORM(Kbetween) ONCE(PatLeast() || PgreaterThan())
    && (PatMost() || PlessThan())
ENDFORM Pblock IS FORM(Kblock)
REPEAT Pstatement()
ENDFORM Pboolean IS FORM(Kboolean)
REPEAT PbooleanValue() || PbooleanDisplay() || Pboolean()
ENDFORM PbooleanDisplay IS FORM(KbooleanDisplay)
ONCE PbooleanValue()
REPEAT Pdisplay()
ENDFORM PbooleanMap IS FORM(KbooleanMap)
ONCE PbooleanValue()
ENDFORM PbooleanValue IS ONCE Pfalse() || Ptrue() || PvalueNameRef()
    || Pand() || Por() || Pnot() || Pxor() || Pequal() || Pincreasing()
    || PstrictlyIncreasing()
END PborderPattern IS FORM(KborderPattern)
ONCE PintegerValue() && PintegerValue() && Pboolean()
ENDFORM PborderWidth IS FORM(KborderWidth)
ONCE PintegerValue()
ENDFORM PboundingBox IS FORM(KboundingBox)
ONCE Prectangle()
ENDFORM Pbuild IS FORM(Kbuild)
ONCE PkeywordNameRef()
REPEAT Pliteral() || Pactual() || Pbuild() || PforEach() || Pcomment()
ENDFORM Pceiling IS FORM(Kceiling)
ONCE PnumberValue()
ENDFORM Pcell IS ZERO(n) ZERO(m) FORM(Kcell)
ONCE PcellNameDef() && PcellType()
REPEAT G1(n, Pstatus) || Pview() || G1(m, PviewMap) || Pproperty()
    || Pcomment() || PuserData()
ENDFORM PcellNameDef IS ONCE PnameDef()
END PcellNameRef IS ONCE PnameRef()
END PcellRef IS FORM(KcellRef)
ONCE PcellNameRef()
OPTIONAL PlibraryRef()
ENDFORM PcellType IS FORM(KcellType)
ONCE MATCH(KGENERIC) || MATCH(KTIE) || MATCH(KRIPPER)
ENDFORM Pchange IS FORM(Kchange)
ONCE PportNameRef() || PportRef() || PportList()
OPTIONAL Ptransition() || Pbecomes()
ENDFORM Pcircle IS FORM(Kcircle)
ONCE PpointValue() && PpointValue()
REPEAT Pproperty()
ENDFORM Pcollector IS FORM(Kcollector)
ENDFORM Pcolor IS FORM(Kcolor)
ONCE PscaledInteger() && PscaledInteger() && PscaledInteger()
ENDFORM Pcomment IS CONDFORM(Kcomment, COMMENT)
REPEAT PstringToken()
ENDFORM PcommentGraphics IS ZERO(n) FORM(KcommentGraphics)
REPEAT Pannotate() || Pfigure() || Pinstance() || G1(n, PboundingBox)
    || Pproperty() || Pcomment() || PuserData()
ENDFORM Pcompound IS FORM(Kcompound)
REPEAT PlogicNameRef()
ENDFORM Pconcat IS FORM(Kconcat)
REPEAT PstringValue()
ENDFORM PconnectLocation IS FORM(KconnectLocation)
REPEAT Pfigure()
ENDFORM Pconstant IS FORM(Kconstant)
ONCE PvalueNameDef() && PtypedValue()
ENDFORM Pconstraint IS FORM(Kconstraint)
ONCE PbooleanValue()
REPEAT Pproperty()
ENDFORM Pcontents IS ZERO(n) FORM(Kcontents) FLAG(Fcont)
REPEAT Pinstance() || PoffPageConnector() || Pfigure() || Psection()
    || Pnet() || PnetBundle() || Ppage() || PcommentGraphics()
    || PportImplementation() || Ptiming() || Psimulate() || Pwhen()
    || Pfollow() || PlogicPort() || G1(n, PboundingBox) || Pconstant()
    || Pconstraint() || Pvariable() || Passign() || Pblock() || Pif()
    || Piterate() || Pwhile() || Pproperty() || Pcomment()
    || PuserData() UNFLAG(Fcont)
ENDFORM PcornerType IS FORM(KcornerType)
ONCE MATCH(KEXTEND) || MATCH(KROUND) || MATCH(KTRUNCATE)
ENDFORM Pcriticality IS FORM(Kcriticality)
ONCE PintegerValue() || PintegerDisplay()
ENDFORM PcurrentMap IS FORM(KcurrentMap)
ONCE PmiNoMaxValue()
ENDFORM Pcurve IS FORM(Kcurve)
REPEAT Parc() || PpointValue()
ENDFORM Pcycle IS FORM(Kcycle)
ONCE PintegerValue()
OPTIONAL Pduration()
ENDFORM PdataOrigin IS FORM(KdataOrigin)
ONCE PstringToken()
OPTIONAL Pversion()
ENDFORM PdcFaninLoad IS FORM(KdcFaninLoad)
ONCE PnumberValue() || PnumberDisplay()
ENDFORM PdcFanoutLoad IS FORM(KdcFanoutLoad)
ONCE PnumberValue() || PnumberDisplay()
ENDFORM PdcMaxFanin IS FORM(KdcMaxFanin)
ONCE PnumberValue() || PnumberDisplay()
ENDFORM PdcMaxFanout IS FORM(KdcMaxFanout)
ONCE PnumberValue() || PnumberDisplay()
ENDFORM Pdelay IS FORM(Kdelay)
ONCE PmiNoMaxValue() || PmiNoMaxDisplay()
ENDFORM Pdelta IS FORM(Kdelta)
REPEAT PpointValue()
ENDFORM Pderivation IS FORM(Kderivation)
ONCE MATCH(KCALCULATED) || MATCH(KMEASURED) || MATCH(KREQUIRED)
ENDFORM Pdesign IS ZERO(n) FORM(Kdesign)
ONCE PdesignNameDef() && PcellRef()
REPEAT G1(n, Pstatus) || Pproperty() || Pcomment() || PuserData()
ENDFORM Pdesignator IS FORM(Kdesignator)
ONCE PstringValue() || PstringDisplay()
ENDFORM PdesignNameDef IS ONCE PnameDef()
END Pdifference IS FORM(Kdifference)
ONCE PfigureGroupRef() || PfigureOp()
REPEAT PfigureGroupRef() || PfigureOp()
ENDFORM Pdirection IS FORM(Kdirection)
ONCE MATCH(KINOUT) || MATCH(KINPUT) || MATCH(KOUTPUT)
ENDFORM Pdisplay IS FORM(Kdisplay)
ONCE PfigureGroupNameRef() || PfigureGroupOverride()
OPTIONAL Pjustify()
OPTIONAL Porientation()
OPTIONAL Porigin()
ENDFORM Pdivide IS FORM(Kdivide)
ONCE PnumberValue()
REPEAT PnumberValue()
ENDFORM Pdominates IS FORM(Kdominates)
REPEAT PlogicNameRef()
ENDFORM Pdot IS FORM(Kdot)
ONCE PpointValue()
REPEAT Pproperty()
ENDFORM Pduration IS FORM(Kduration)
ONCE PnumberValue()
ENDFORM Pe IS FORM(Ke)
ONCE PintegerToken() && PintegerToken()
ENDFORM Pedif IS                /* root production rule, called externally */
ZERO(n) FORM(Kedif)
ONCE PedifFileNameDef() && PedifVersion() && PedifLevel() && PkeywordMap()
REPEAT G1(n, Pstatus) || Pexternal() || Plibrary() || Pdesign()
    || Pcomment() || PuserData()
ENDFORM PedifFileNameDef IS ONCE PnameDef()
END PedifLevel IS FORM(KedifLevel)
ONCE PintegerToken()
ENDFORM PedifVersion IS FORM(KedifVersion)
ONCE PintegerToken() && PintegerToken() && PintegerToken()
ENDFORM Pelse IS FORM(Kelse)
REPEAT Pstatement()
ENDFORM PenclosureDistance IS FORM(KenclosureDistance)
ONCE PruleNameDef() && PfigureGroupObject() && PfigureGroupObject()
    && (Prange() || PsingleValueSet())
REPEAT Pcomment() || PuserData()
ENDFORM PendType IS FORM(KendType)
ONCE MATCH(KEXTEND) || MATCH(KROUND) || MATCH(KTRUNCATE)
ENDFORM Pentry IS FORM(Kentry) ONCE(Pmatch() || Pchange() || Psteady())
    && (PlogicRef() || PportRef() || PnoChange() || Ptable())
OPTIONAL Pdelay() || PloadDelay()
ENDFORM Pescape IS FORM(Kescape)
ENDFORM Pequal IS FORM(Kequal)
ONCE PnumberValue()
REPEAT PnumberValue()
ENDFORM Pevent IS FORM(Kevent)
ONCE PportRef() || PportList() || PportGroup() || PnetRef() || PnetGroup()
REPEAT Ptransition() || Pbecomes()
ENDFORM Pexactly IS FORM(Kexactly)
ONCE PnumberValue()
ENDFORM Pexternal IS ZERO(n) FORM(Kexternal) FLAG(Fext)
ONCE PlibraryNameDef() && PedifLevel() && Ptechnology()
REPEAT G1(n, Pstatus) || Pcell() || Pcomment() || PuserData() UNFLAG(Fext)
ENDFORM Pfabricate IS FORM(Kfabricate)
ONCE PlayerNameDef() && PfigureGroupNameRef()
ENDFORM Pfalse IS FORM(Kfalse)
ENDFORM Pfigure IS FORM(Kfigure)
ONCE PfigureGroupNameRef() || PfigureGroupOverride()
REPEAT Pcircle() || Pdot() || PopenShape() || Ppath() || Ppolygon()
    || Prectangle() || Pshape() || Pcomment() || PuserData()
ENDFORM PfigureArea IS FORM(KfigureArea)
ONCE PruleNameDef() && PfigureGroupObject() && (Prange()
                                                || PsingleValueSet())
REPEAT Pcomment() || PuserData()
ENDFORM PfigureGroup IS ZERO(m) ZERO(n) ZERO(o) ZERO(p) ZERO(q) ZERO(r)
ZERO(s) ZERO(t) ZERO(u) FORM(KfigureGroup)
ONCE PfigureGroupNameDef()
REPEAT G1(m, PcornerType) || G1(n, PendType) || G1(o, PpathWidth)
    || G1(p, PborderWidth) || G1(q, Pcolor) || G1(r, PfillPattern)
    || G1(s, PborderPattern) || G1(t, PtextHeight) || G1(u, Pvisible)
    || PincludeFigureGroup() || Pproperty() || Pcomment() || PuserData()
ENDFORM PfigureGroupNameDef IS ONCE PnameDef()
END PfigureGroupNameRef IS ONCE PnameRef()
END PfigureGroupObject IS FORM(KfigureGroupObject)
ONCE PfigureGroupNameRef() || PfigureGroupRef() || PfigureOp()
ENDFORM PfigureGroupOverride IS ZERO(m) ZERO(n) ZERO(o) ZERO(p) ZERO(q)
ZERO(r) ZERO(s) ZERO(t) ZERO(u) FORM(KfigureGroupOverride)
ONCE PfigureGroupNameRef()
REPEAT G1(m, PcornerType) || G1(n, PendType) || G1(o, PpathWidth)
    || G1(p, PborderWidth) || G1(q, Pcolor) || G1(r, PfillPattern)
    || G1(s, PborderPattern) || G1(t, PtextHeight) || G1(u, Pvisible)
    || Pproperty() || Pcomment() || PuserData()
ENDFORM PfigureGroupRef IS FORM(KfigureGroupRef)
ONCE PfigureGroupNameRef()
OPTIONAL PlibraryRef()
ENDFORM PfigureOp IS ONCE Pdifference() || Pintersection() || Pinverse()
    || Poversize() || Punion()
END PfigurePerimeter IS FORM(KfigurePerimeter)
ONCE PruleNameDef() && PfigureGroupObject() && (Prange()
                                                || PsingleValueSet())
REPEAT Pcomment() || PuserData()
ENDFORM PfigureWidth IS FORM(KfigureWidth)
ONCE PruleNameDef() && PfigureGroupObject() && (Prange()
                                                || PsingleValueSet())
REPEAT Pcomment() || PuserData()
ENDFORM PfillPattern IS FORM(KfillPattern)
ONCE PintegerValue() && PintegerValue() && Pboolean()
ENDFORM Pfix IS FORM(Kfix)
ONCE PnumberValue()
ENDFORM Pfloor IS FORM(Kfloor)
ONCE PnumberValue()
ENDFORM Pfollow IS FORM(Kfollow) ONCE(PportNameRef() || PportRef())
    && (PportRef() || Ptable())
OPTIONAL Pdelay() || PloadDelay()
ENDFORM PforbiddenEvent IS FORM(KforbiddenEvent)
ONCE PtimeInterval()
REPEAT Pevent()
ENDFORM PforEach IS FORM(KforEach)
ONCE PformalNameRef() || PformalList()
REPEAT Pbuild() || Pactual() || Pliteral() || PforEach() || Pcomment()
ENDFORM Pform IS if (!ISKEYWORD(token->type))
    return (FALSE);

else
    add_token();
REPEAT PintegerToken() || PstringToken() || Pidentifier() || Pform()
ENDFORM Pformal IS FORM(Kformal)
ONCE PformalNameDef()
REPEAT Poptional() || Pcollector()
ENDFORM PformalList IS FORM(KformalList)
REPEAT PformalNameRef()
ENDFORM PformalNameDef IS ONCE Pidentifier()
END PformalNameRef IS ONCE Pidentifier()
END Pgenerate IS FORM(Kgenerate)
REPEAT Pliteral() || Pactual() || Pbuild() || PforEach() || Pcomment()
ENDFORM PglobalPortRef IS FORM(KglobalPortRef)
ONCE PportNameRef()
ENDFORM PgreaterThan IS FORM(KgreaterThan)
ONCE PnumberValue()
ENDFORM PgridMap IS FORM(KgridMap)
ONCE PnumberValue() && PnumberValue()
ENDFORM Pidentifier IS if (token->type != IDENT)
    return (FALSE);

else
{
if (Fvref && !Fassign)
    token->type = VALUEREF;
Fvref = Fassign = 0;
add_token();
return (TRUE);
}
}

Pif IS FORM(Kif)
ONCE PbooleanValue() && Pthen()
OPTIONAL Pelse()
ENDFORM Pignore IS FORM(Kignore)
ENDFORM PincludeFigureGroup IS FORM(KincludeFigureGroup)
ONCE PfigureGroupRef() || PfigureOp()
ENDFORM Pincreasing IS FORM(Kincreasing)
ONCE PnumberValue()
REPEAT PnumberValue()
ENDFORM Pinitial IS FORM(Kinitial)
ENDFORM Pinstance IS ZERO(n) ZERO(m) FORM(Kinstance)
ONCE PinstanceNameDef() && (PviewRef() || PviewList())
REPEAT G1(n, Ptransform) || PparameterAssign() || PportInstance()
    || G1(m, Pdesignator) || Ptiming() || Pproperty() || Pcomment()
    || PuserData()
ENDFORM PinstanceBackAnnotate IS ZERO(n) FORM(KinstanceBackAnnotate)
ONCE PinstanceRef()
REPEAT G1(n, Pdesignator) || Ptiming() || Pproperty() || Pcomment()
ENDFORM PinstanceGroup IS FORM(KinstanceGroup)
REPEAT PinstanceRef()
ENDFORM PinstanceMap IS FORM(KinstanceMap)
REPEAT PinstanceRef() || PinstanceGroup() || Pcomment() || PuserData()
END PinstanceNameDef IS ONCE PnameDef() || Parray()
END PinstanceNameRef IS ONCE PnameRef() || Pmember()
END PinstanceRef IS FORM(KinstanceRef)
ONCE PinstanceNameRef()
OPTIONAL PinstanceRef() || PviewRef()
ENDFORM Pinteger IS FORM(Kinteger)
REPEAT PintegerValue() || PintegerDisplay() || Pinteger()
ENDFORM PintegerDisplay IS FORM(KintegerDisplay)
ONCE PintegerValue()
REPEAT Pdisplay()
ENDFORM PintegerToken IS if (token->type != NUMBER)
    return (FALSE);

else
    add_token();
return (TRUE);
}

PintegerValue IS ONCE PintegerToken() || PvalueNameRef() || Pfloor()
    || Pceiling() || Pfix() || Pmod() || PxCoord() || PyCoord() || Pabs()
    || Pmax() || Pmin() || Pnegate() || Pproduct() || Psubtract() || Psum()
END Pinterface IS ZERO(k) ZERO(l) ZERO(m) ZERO(n) FORM(Kinterface)
FLAG(Fintf)
REPEAT Pport() || PportBundle() || G1(k, Psymbol)
    || G1(l, PprotectionFrame) || G1(m, ParrayRelatedInfo) || Pparameter()
    || Pjoined() || PmustJoin() || PweakJoined() || Ppermutable()
    || Ptiming() || Psimulate() || G1(n, Pdesignator) || Pconstant()
    || Pconstraint() || Pvariable() || Passign() || Pblock() || Pif()
    || Piterate() || Pwhile() || Pproperty() || Pcomment()
    || PuserData() UNFLAG(Fintf)
ENDFORM PinterFigureGroupSpacing IS FORM(KinterFigureGroupSpacing)
ONCE PruleNameDef() && PfigureGroupObject() && PfigureGroupObject()
    && (Prange() || PsingleValueSet())
REPEAT Pcomment() || PuserData()
ENDFORM Pintersection IS FORM(Kintersection)
ONCE PfigureGroupRef() || PfigureOp()
REPEAT PfigureGroupRef() || PfigureOp()
ENDFORM PintraFigureGroupSpacing IS FORM(KintraFigureGroupSpacing)
ONCE PruleNameDef() && PfigureGroupObject() && (Prange()
                                                || PsingleValueSet())
REPEAT Pcomment() || PuserData()
ENDFORM Pinverse IS FORM(Kinverse)
ONCE PfigureGroupRef() || PfigureOp()
ENDFORM Pisolated IS FORM(Kisolated)
ENDFORM Piterate IS FORM(Kiterate)
REPEAT Pstatement()
ENDFORM Pjoined IS FORM(Kjoined)
REPEAT PportRef() || PportList() || PglobalPortRef()
ENDFORM Pjustify IS FORM(Kjustify)
ONCE MATCH(KUPPERLEFT) || MATCH(KUPPERCENTER) || MATCH(KUPPERRIGHT)
    || MATCH(KCENTERLEFT) || MATCH(KCENTERCENTER) || MATCH(KCENTERRIGHT)
    || MATCH(KLOWERLEFT) || MATCH(KLOWERCENTER) || MATCH(KLOWERRIGHT)
ENDFORM PkeywordAlias IS FORM(KkeywordAlias)
ONCE PkeywordNameDef() && PkeywordNameRef()
ENDFORM PkeywordDefine IS FORM(KkeywordDefine)
ONCE PkeywordNameDef() && PkeywordParameters() && Pgenerate()
ENDFORM PkeywordDisplay IS FORM(KkeywordDisplay)
ONCE PkeywordNameRef()
REPEAT Pdisplay()
ENDFORM PkeywordLevel IS FORM(KkeywordLevel)
ONCE PintegerToken()
ENDFORM PkeywordMap IS FORM(KkeywordMap)
ONCE PkeywordLevel()
REPEAT PkeywordAlias() || PkeywordDefine() || Pcomment()
ENDFORM PkeywordNameDef IS ONCE Pidentifier()
END PkeywordNameRef IS ONCE Pidentifier()
END PkeywordParameters IS FORM(KkeywordParameters)
REPEAT Pformal()
ENDFORM PlayerNameDef IS ONCE PnameDef()
END PlessThan IS FORM(KlessThan)
ONCE PnumberValue()
END Plibrary IS ZERO(n) FORM(Klibrary)
ONCE PlibraryNameDef() && PedifLevel() && Ptechnology()
REPEAT G1(n, Pstatus) || Pcell() || Pcomment() || PuserData()
ENDFORM PlibraryNameDef IS ONCE PnameDef()
END PlibraryNameRef IS ONCE PnameRef()
END PlibraryRef IS FORM(KlibraryRef)
ONCE PlibraryNameRef()
ENDFORM PlistOfNets IS FORM(KlistOfNets)
REPEAT Pnet()
ENDFORM PlistOfPorts IS FORM(KlistOfPorts)
REPEAT Pport() || PportBundle()
ENDFORM Pliteral IS FORM(Kliteral)
REPEAT PintegerToken() || PstringToken() || Pidentifier() || Pform()
ENDFORM PloadDelay IS FORM(KloadDelay) ONCE(PmiNoMaxValue()
                                            || PmiNoMaxDisplay())
    && (PmiNoMaxValue() || PmiNoMaxDisplay())
ENDFORM PlogicAssign IS FORM(KlogicAssign) ONCE(PportNameRef()
                                                || PportRef())
    && (PportRef() || PlogicRef() || Ptable())
OPTIONAL Pdelay() || PloadDelay()
ENDFORM PlogicInput IS FORM(KlogicInput) ONCE(PportNameRef() || PportRef()
                                              || PportList())
    && PlogicWaveform()
ENDFORM PlogicList IS FORM(KlogicList)
REPEAT PlogicNameRef() || PlogicOneOf() || Pignore()
ENDFORM PlogicMapInput IS FORM(KlogicMapInput)
REPEAT PlogicRef()
ENDFORM PlogicMapOutput IS FORM(KlogicMapOutput)
REPEAT PlogicRef()
ENDFORM PlogicNameDef IS ONCE PnameDef()
END PlogicNameRef IS ONCE PnameRef()
END PlogicOneOf IS FORM(KlogicOneOf)
REPEAT PlogicNameRef() || PlogicList()
ENDFORM PlogicOutput IS FORM(KlogicOutput) ONCE(PportNameRef()
                                                || PportRef()
                                                || PportList())
    && PlogicWaveform()
ENDFORM PlogicPort IS CONDFORM(KlogicPort, LOGICMODEL)
ONCE PportNameDef()
REPEAT Pproperty() || Pcomment() || PuserData()
ENDFORM PlogicRef IS FORM(KlogicRef)
ONCE PlogicNameRef()
OPTIONAL PlibraryRef()
ENDFORM PlogicValue IS ZERO(m) ZERO(n) ZERO(o) ZERO(p) ZERO(q) ZERO(r)
ZERO(s) ZERO(t) ZERO(u) ZERO(v) FORM(KlogicValue)
ONCE PlogicNameDef()
REPEAT G1(m, PvoltageMap) || G1(n, PcurrentMap) || G1(o, PbooleanMap)
    || G1(p, Pcompound) || G1(q, Pweak) || G1(r, Pstrong)
    || G1(s, Pdominates) || G1(t, PlogicMapOutput) || G1(u, PlogicMapInput)
    || G1(v, Pisolated) || Presolves() || Pproperty() || Pcomment()
    || PuserData()
ENDFORM PlogicWaveform IS FORM(KlogicWaveform)
REPEAT PlogicNameRef() || PlogicList() || PlogicOneOf() || Pignore()
ENDFORM Pmaintain IS FORM(Kmaintain)
ONCE PportNameRef() || PportRef()
OPTIONAL Pdelay() || PloadDelay()
ENDFORM Pmatch IS FORM(Kmatch) ONCE(PportNameRef() || PportRef()
                                    || PportList()) && (PlogicNameRef()
                                                        || PlogicList()
                                                        || PlogicOneOf())
ENDFORM Pmax IS FORM(Kmax)
ONCE PnumberValue()
REPEAT PnumberValue()
ENDFORM Pmember IS FORM(Kmember)
ONCE PnameRef() && PintegerValue()
REPEAT PintegerValue()
ENDFORM Pmin IS FORM(Kmin)
ONCE PnumberValue()
REPEAT PnumberValue()
ENDFORM PmiNoMax IS FORM(KmiNoMax)
REPEAT PmiNoMaxValue() || PmiNoMaxDisplay() || PmiNoMax()
ENDFORM PmiNoMaxDisplay IS FORM(KmiNoMaxDisplay)
ONCE PmiNoMaxValue()
REPEAT Pdisplay()
ENDFORM PmiNoMaxValue IS ONCE PnumberValue() || Pmnm()
END Pmnm IS FORM(Kmnm) ONCE(PnumberValue() || Pundefined()
                            || Punconstrained()) && (PnumberValue()
                                                     || Pundefined()
                                                     || Punconstrained())
    && (PnumberValue() || Pundefined() || Punconstrained())
ENDFORM Pmod IS FORM(Kmod)
ONCE PintegerValue() && PintegerValue()
ENDFORM PmultipleValueSet IS FORM(KmultipleValueSet)
REPEAT PrangeVector()
ENDFORM PmustJoin IS FORM(KmustJoin)
REPEAT PportRef() || PportList() || PweakJoined() || Pjoined()
ENDFORM Pname IS FORM(Kname)
ONCE Pidentifier()
REPEAT Pdisplay()
ENDFORM PnameDef IS ONCE Pidentifier() || Pname() || Prename()
END PnameRef IS ONCE Pidentifier() || Pname()
END Pnegate IS FORM(Knegate)
ONCE PnumberValue()
ENDFORM Pnet IS ZERO(n) FORM(Knet)
ONCE PnetNameDef() && Pjoined()
REPEAT G1(n, Pcriticality) || PnetDelay() || Pfigure() || Pnet()
    || Pinstance() || PcommentGraphics() || Pproperty() || Pcomment()
    || PuserData()
ENDFORM PnetBackAnnotate IS ZERO(n) FORM(KnetBackAnnotate)
ONCE PnetRef()
REPEAT PnetDelay() || G1(n, Pcriticality) || Pproperty() || Pcomment()
ENDFORM PnetBundle IS FORM(KnetBundle)
ONCE PnetNameDef() && PlistOfNets()
REPEAT Pfigure() || PcommentGraphics() || Pproperty() || Pcomment()
    || PuserData()
ENDFORM PnetDelay IS FORM(KnetDelay)
ONCE Pderivation() && Pdelay()
REPEAT Ptransition() || Pbecomes()
ENDFORM PnetGroup IS FORM(KnetGroup)
REPEAT PnetNameRef() || PnetRef()
ENDFORM PnetMap IS FORM(KnetMap)
REPEAT PnetRef() || PnetGroup() || Pcomment() || PuserData()
ENDFORM PnetNameDef IS ONCE PnameDef() || Parray()
END PnetNameRef IS ONCE PnameRef() || Pmember()
END PnetRef IS FORM(KnetRef)
ONCE PnetNameRef()
REPEAT PnetRef() || PinstanceRef() || PviewRef()
ENDFORM PnoChange IS FORM(KnoChange)
ENDFORM PnonPermutable IS FORM(KnonPermutable)
REPEAT PportRef() || Ppermutable()
ENDFORM Pnot IS FORM(Knot)
ONCE PbooleanValue()
ENDFORM PnotAllowed IS FORM(KnotAllowed)
ONCE PruleNameDef() && PfigureGroupObject()
REPEAT Pcomment() && PuserData()
ENDFORM PnotchSpacing IS FORM(KnotchSpacing)
ONCE PruleNameDef() && PfigureGroupObject() && (Prange()
                                                || PsingleValueSet())
REPEAT Pcomment() && PuserData()
ENDFORM Pnumber IS FORM(Knumber)
REPEAT PnumberValue() || PnumberDisplay() || Pnumber()
ENDFORM PnumberDefinition IS ZERO(n) FORM(KnumberDefinition)
REPEAT Pscale() || G1(n, PgridMap) || Pcomment()
ENDFORM PnumberDisplay IS FORM(KnumberDisplay)
ONCE PnumberValue()
REPEAT Pdisplay()
ENDFORM PnumberValue IS ONCE PscaledInteger() || PvalueNameRef()
    || Pfloor() || Pceiling() || Pfix() || Pmod() || PxCoord() || PyCoord()
    || Pdivide() || Pabs() || Pmax() || Pmin() || Pnegate() || Pproduct()
    || Psubtract() || Psum()
END PoffPageConnector IS ZERO(n) FORM(KoffPageConnector)
ONCE PportNameDef()
REPEAT G1(n, Punused) || Pproperty() || Pcomment() || PuserData()
ENDFORM PoffsetEvent IS FORM(KoffsetEvent)
ONCE Pevent() && PnumberValue()
ENDFORM PopenShape IS FORM(KopenShape)
ONCE Pcurve()
REPEAT Pproperty()
ENDFORM Poptional IS FORM(Koptional)
ONCE Pliteral() || Pactual() || Pbuild()
ENDFORM Por IS FORM(Kor)
REPEAT PbooleanValue()
ENDFORM Porientation IS FORM(Korientation)
ONCE MATCH(KR0) || MATCH(KR90) || MATCH(KR180) || MATCH(KR270)
    || MATCH(KMX) || MATCH(KMY) || MATCH(KMYR90) || MATCH(KMXR90)
ENDFORM Porigin IS FORM(Korigin)
ONCE PpointValue()
ENDFORM PoverhangDistance IS FORM(KoverhangDistance)
ONCE PruleNameDef() && PfigureGroupObject() && PfigureGroupObject()
    && (Prange() || PsingleValueSet())
REPEAT Pcomment() || PuserData()
ENDFORM PoverlapDistance IS FORM(KoverlapDistance)
ONCE PruleNameDef() && PfigureGroupObject() && PfigureGroupObject()
    && (Prange() || PsingleValueSet())
REPEAT Pcomment() || PuserData()
ENDFORM Poversize IS FORM(Koversize)
ONCE PintegerValue() && (PfigureGroupRef() || PfigureOp()) && PcornerType()
ENDFORM Powner IS FORM(Kowner)
ONCE PstringToken()
ENDFORM Ppage IS ZERO(n) ZERO(m) FORM(Kpage) FLAG(Fpage)
ONCE PinstanceNameDef()
REPEAT Pinstance() || Pnet() || PnetBundle() || PcommentGraphics()
    || PportImplementation() || G1(n, PpageSize) || G1(m, PboundingBox)
    || Pconstant() || Pconstraint() || Pvariable() || Passign() || Pblock()
    || Pif() || Piterate() || Pwhile() || Pcomment()
    || PuserData() UNFLAG(Fpage)
ENDFORM PpageSize IS FORM(KpageSize)
ONCE Prectangle()
ENDFORM Pparameter IS FORM(Kparameter)
ONCE PvalueNameDef() && PtypedValue()
OPTIONAL Punit()
ENDFORM PparameterAssign IS FORM(KparameterAssign) FLAG(Fassign)
ONCE PvalueNameRef() && PtypedValue()
ENDFORM PparameterDisplay IS FORM(KparameterDisplay)
ONCE PvalueNameRef()
REPEAT Pdisplay()
ENDFORM Ppath IS FORM(Kpath)
ONCE PpointList()
REPEAT Pproperty()
ENDFORM PpathDelay IS FORM(KpathDelay)
ONCE Pdelay()
REPEAT Pevent()
ENDFORM PpathWidth IS FORM(KpathWidth)
ONCE PintegerValue()
ENDFORM Ppermutable IS FORM(Kpermutable)
REPEAT PportRef() || Ppermutable() || PnonPermutable()
ENDFORM PphysicalDesignRule IS FORM(KphysicalDesignRule)
REPEAT PfigureWidth() || PfigureArea() || PrectangleSize()
    || PfigurePerimeter() || PoverlapDistance() || PoverhangDistance()
    || PenclosureDistance() || PinterFigureGroupSpacing()
    || PintraFigureGroupSpacing() || PnotchSpacing() || PnotAllowed()
    || PfigureGroup() || Pcomment() || PuserData()
ENDFORM Pplug IS FORM(Kplug)
REPEAT PsocketSet()
ENDFORM Ppoint IS CONDFORM(Kpoint, GRAPHIC)
REPEAT PpointValue() || PpointDisplay() || Ppoint()
ENDFORM PpointDisplay IS FORM(KpointDisplay)
ONCE PpointValue()
REPEAT Pdisplay()
ENDFORM PpointList IS FORM(KpointList)
REPEAT PpointValue()
ENDFORM PpointSubtract IS FORM(KpointSubtract)
ONCE PpointValue()
REPEAT PpointValue()
ENDFORM PpointSum IS FORM(KpointSum)
REPEAT PpointValue()
ENDFORM PpointValue IS ONCE Ppt() || PvalueNameRef() || PpointSum()
    || PpointSubtract()
END Ppolygon IS FORM(Kpolygon)
ONCE PpointList()
REPEAT Pproperty()
END Pport IS ZERO(i) ZERO(j) ZERO(k) ZERO(l) ZERO(m) ZERO(n) ZERO(o)
ZERO(p) FORM(Kport)
ONCE PportNameDef()
REPEAT G1(i, Pdirection) || G1(j, Punused) || G1(k, Pdesignator)
    || G1(l, PdcFaninLoad) || G1(m, PdcFanoutLoad) || G1(n, PdcMaxFanin)
    || G1(o, PdcMaxFanout) || G1(p, PacLoad) || PportDelay() || Pproperty()
    || Pcomment() || PuserData()
ENDFORM PportBackAnnotate IS ZERO(m) ZERO(n) ZERO(o) ZERO(p) ZERO(q)
ZERO(r) FORM(KportBackAnnotate)
ONCE PportRef()
REPEAT G1(m, Pdesignator) || G1(n, PdcFaninLoad) || G1(o, PdcFanoutLoad)
    || G1(p, PdcMaxFanin) || G1(q, PdcMaxFanout) || G1(r, PacLoad)
    || PportDelay() || Pproperty() || Pcomment()
ENDFORM PportBundle IS FORM(KportBundle)
ONCE PportNameDef() && PlistOfPorts()
REPEAT Pproperty() || Pcomment() || PuserData()
ENDFORM PportDelay IS FORM(KportDelay)
ONCE Pderivation() && (Pdelay() || PloadDelay())
REPEAT Ptransition() || Pbecomes()
ENDFORM PportGroup IS FORM(KportGroup)
REPEAT PportNameRef() || PportRef()
ENDFORM PportImplementation IS ZERO(m) FORM(KportImplementation)
ONCE PportNameRef() || PportRef()
REPEAT G1(m, PconnectLocation) || Pfigure() || Pinstance()
    || PcommentGraphics() || PpropertyDisplay() || PkeywordDisplay()
    || Pproperty() || Pcomment() || PuserData()
ENDFORM PportInstance IS ZERO(j) ZERO(k) ZERO(l) ZERO(m) ZERO(n) ZERO(o)
ZERO(p) FORM(KportInstance)
ONCE PportNameRef() || PportRef()
REPEAT G1(j, Punused) || G1(k, Pdesignator) || G1(l, PdcFaninLoad)
    || G1(m, PdcFanoutLoad) || G1(n, PdcMaxFanin) || G1(o, PdcMaxFanout)
    || G1(p, PacLoad) || PportDelay() || Pproperty() || Pcomment()
    || PuserData()
ENDFORM PportList IS FORM(KportList)
REPEAT PportNameRef() || PportRef()
ENDFORM PportListAlias IS FORM(KportListAlias)
ONCE PportNameDef() && PportList()
ENDFORM PportMap IS FORM(KportMap)
REPEAT PportRef() || PportGroup() || Pcomment() || PuserData()
ENDFORM PportNameDef IS ONCE PnameDef() || Parray()
END PportNameRef IS ONCE PnameRef() || Pmember()
END PportRef IS FORM(KportRef)
ONCE PportNameRef()
OPTIONAL PportRef() || PinstanceRef() || PviewRef()
ENDFORM Pproduct IS FORM(Kproduct)
REPEAT PnumberValue()
ENDFORM Pprogram IS FORM(Kprogram)
ONCE PstringToken()
OPTIONAL Pversion()
ENDFORM Pproperty IS ZERO(n) ZERO(m) FORM(Kproperty)
ONCE PpropertyNameDef() && PtypedValue()
REPEAT G1(n, Powner) || G1(m, Punit) || Pproperty() || Pcomment()
ENDFORM PpropertyDisplay IS FORM(KpropertyDisplay)
ONCE PpropertyNameRef()
REPEAT Pdisplay()
ENDFORM PpropertyNameDef IS ONCE PnameDef()
END PpropertyNameRef IS ONCE PnameRef()
END PprotectionFrame IS ZERO(m) CONDFORM(KprotectionFrame, GRAPHIC)
REPEAT PportImplementation() || Pfigure() || Pinstance()
    || PcommentGraphics() || G1(m, PboundingBox) || PpropertyDisplay()
    || PkeywordDisplay() || PparameterDisplay() || Pproperty()
    || Pcomment() || PuserData()
ENDFORM Ppt IS FORM(Kpt)
ONCE PintegerValue() && PintegerValue()
ENDFORM Prange IS ONCE PatLeast() || PatMost() || Pbetween() || Pexactly()
    || PgreaterThan() || PlessThan()
END PrangeVector IS FORM(KrangeVector)
REPEAT Prange() || PsingleValueSet()
ENDFORM Prectangle IS FORM(Krectangle)
ONCE PpointValue() && PpointValue()
REPEAT Pproperty()
ENDFORM PrectangleSize IS FORM(KrectangleSize)
ONCE PruleNameDef() && PfigureGroupObject() && (PrangeVector()
                                                || PmultipleValueSet())
REPEAT Pcomment() || PuserData()
ENDFORM Prename IS FORM(Krename) ONCE(Pidentifier() || Pname())
    && (PstringToken() || PstringDisplay())
ENDFORM Presolves IS FORM(Kresolves)
REPEAT PlogicNameRef()
ENDFORM PruleNameDef IS ONCE PnameDef()
END Pscale IS FORM(Kscale)
ONCE PnumberValue() && PnumberValue() && Punit()
ENDFORM PscaledInteger IS ONCE PintegerToken() || Pe()
END PscaleX IS FORM(KscaleX)
ONCE PintegerValue() && PintegerValue()
ENDFORM PscaleY IS FORM(KscaleY)
ONCE PintegerValue() && PintegerValue()
ENDFORM Psection IS FORM(Ksection)
ONCE PstringValue()
REPEAT PstringValue() || Psection() || Pinstance()
ENDFORM Pshape IS FORM(Kshape)
ONCE Pcurve()
REPEAT Pproperty()
ENDFORM Psimulate IS CONDFORM(Ksimulate, LOGICMODEL)
ONCE PsimulateNameDef()
REPEAT PportListAlias() || PwaveValue() || Papply() || Pcomment()
    || PuserData()
ENDFORM PsimulateNameDef IS ONCE PnameDef()
END PsimulationInfo IS CONDFORM(KsimulationInfo, LOGICMODEL)
REPEAT PlogicValue() || Pcomment() || PuserData()
ENDFORM PsingleValueSet IS FORM(KsingleValueSet)
REPEAT Prange()
ENDFORM Psite IS FORM(Ksite)
ONCE PviewRef()
OPTIONAL Ptransform()
ENDFORM Psocket IS FORM(Ksocket)
OPTIONAL Psymmetry()
ENDFORM PsocketSet IS FORM(KsocketSet)
ONCE Psymmetry()
REPEAT Psite()
ENDFORM Pstatement IS ONCE Pblock() || Pcomment() || Pconstant()
    || Pconstraint() || Pif() || Piterate() || PuserData() || Pwhile()
    || Pescape() || Fintf && Pproperty() || Fcont && (Pfigure()
                                                      || Pfollow()
                                                      || PlogicPort()
                                                      ||
                                                      PoffPageConnector()
                                                      || Psection()
                                                      || Pwhen()) || (Fcont
                                                                      ||
                                                                      Fintf)
    && (Psimulate() || Ptiming()) || (Fcont || Fpage)
    && (PcommentGraphics() || Pinstance() || Pnet() || PnetBundle()
        || PportImplementation()) || (Fcont || Fintf || Fpage)
    && (Pvariable() || Passign())
END Pstatus IS FORM(Kstatus)
REPEAT Pwritten() || Pcomment() || PuserData()
ENDFORM Psteady IS FORM(Ksteady) ONCE(PportNameRef() || PportRef()
                                      || PportList()) && Pduration()
OPTIONAL Ptransition() || Pbecomes()
ENDFORM PstrictlyIncreasing IS FORM(KstrictlyIncreasing)
ONCE PnumberValue()
REPEAT PnumberValue()
ENDFORM Pstring IS FORM(Kstring)
REPEAT PstringValue() || PstringDisplay() || Pstring()
ENDFORM PstringDisplay IS FORM(KstringDisplay)
ONCE PstringValue()
REPEAT Pdisplay()
ENDFORM PstringToken IS if (token->type != STRING)
    return (FALSE);

else
    add_token();
return (TRUE);
}

PstringValue IS ONCE PstringToken() || PvalueNameRef() || Pconcat()
END Pstrong IS FORM(Kstrong)
ONCE PlogicNameRef()
ENDFORM Psubtract IS FORM(Ksubtract)
ONCE PnumberValue()
REPEAT PnumberValue()
ENDFORM Psum IS FORM(Ksum)
REPEAT PnumberValue()
ENDFORM Psymbol IS ZERO(m) ZERO(n) CONDFORM(Ksymbol, GRAPHIC)
REPEAT PportImplementation() || Pfigure() || Pannotate() || Pinstance()
    || PcommentGraphics() || G1(m, PpageSize) || G1(n, PboundingBox)
    || PpropertyDisplay() || PkeywordDisplay() || PparameterDisplay()
    || Pproperty() || Pcomment() || PuserData()
ENDFORM Psymmetry IS FORM(Ksymmetry)
REPEAT Ptransform()
ENDFORM Ptable IS ZERO(m) FORM(Ktable)
REPEAT Pentry() || G1(m, PtableDefault)
ENDFORM PtableDefault IS FORM(KtableDefault)
ONCE PlogicRef() || PportRef() || PnoChange() || Ptable()
OPTIONAL Pdelay() || PloadDelay()
ENDFORM Ptechnology IS ZERO(n) ZERO(m) FORM(Ktechnology) FLAG(Ftech)
ONCE PnumberDefinition()
REPEAT PfigureGroup() || Pfabricate() || G1(n, PsimulationInfo)
    || G1(m, PphysicalDesignRule) || Pconstant() || Pconstraint()
    || Pblock() || Pif() || Piterate() || Pwhile() || Pcomment()
    || PuserData() UNFLAG(Ftech)
ENDFORM Pthen IS FORM(Kthen)
REPEAT Pstatement()
ENDFORM PtextHeight IS FORM(KtextHeight)
ONCE PintegerValue()
ENDFORM PtimeInterval IS FORM(KtimeInterval) ONCE(Pevent()
                                                  || PoffsetEvent())
    && (Pevent() || PoffsetEvent() || Pduration())
ENDFORM PtimeStamp IS FORM(KtimeStamp)
ONCE PintegerToken() && PintegerToken() && PintegerToken()
    && PintegerToken() && PintegerToken() && PintegerToken()
ENDFORM Ptiming IS CONDFORM(Ktiming, LOGICMODEL)
ONCE Pderivation()
REPEAT PpathDelay() || PforbiddenEvent() || Pcomment() || PuserData()
ENDFORM Ptransform IS CONDFORM(Ktransform, GRAPHIC)
OPTIONAL PscaleX()
OPTIONAL PscaleY()
OPTIONAL Pdelta()
OPTIONAL Porientation()
OPTIONAL Porigin()
ENDFORM Ptransition IS FORM(Ktransition) ONCE(PlogicNameRef()
                                              || PlogicList()
                                              || PlogicOneOf())
    && (PlogicNameRef() || PlogicList() || PlogicOneOf())
ENDFORM Ptrigger IS CONDFORM(Ktrigger, LOGICMODEL)
REPEAT Pchange() || Psteady() || Pinitial()
ENDFORM Ptrue IS FORM(Ktrue)
ENDFORM PtypedValue IS ONCE Pboolean() || Pinteger() || PmiNoMax()
    || Pnumber() || Ppoint() || Pstring()
END Punconstrained IS FORM(Kunconstrained)
ENDFORM Pundefined IS FORM(Kundefined)
ENDFORM Punion IS FORM(Kunion)
ONCE PfigureGroupRef() || PfigureOp()
REPEAT PfigureGroupRef() || PfigureOp()
ENDFORM Punit IS FORM(Kunit)
ONCE MATCH(KANGLE) || MATCH(KCAPACITANCE) || MATCH(KCONDUCTANCE)
    || MATCH(KCHARGE) || MATCH(KCURRENT) || MATCH(KDISTANCE)
    || MATCH(KENERGY) || MATCH(KFLUX) || MATCH(KFREQUENCY)
    || MATCH(KINDUCTANCE) || MATCH(KMASS) || MATCH(KPOWER)
    || MATCH(KRESISTANCE) || MATCH(KTEMPERATURE) || MATCH(KTIME)
    || MATCH(KVOLTAGE)
ENDFORM Punused IS FORM(Kunused)
ENDFORM PuserData IS CONDFORM(KuserData, USERDATA)
ONCE Pidentifier()
REPEAT PintegerToken() || PstringToken() || Pidentifier() || Pform()
ENDFORM PvalueNameDef IS ONCE PnameDef() || Parray()
END PvalueNameRef IS FLAG(Fvref)
ONCE PnameRef() || Pmember() UNFLAG(Fvref)
END Pvariable IS FORM(Kvariable)
ONCE PvalueNameDef() && PtypedValue()
ENDFORM Pversion IS FORM(Kversion)
ONCE PstringToken()
ENDFORM Pview IS ZERO(n) ZERO(m) FORM(Kview);

if (Fext)
    m = TRUE                    /* prohibit contents in (external */
        ONCE PviewNameDef() && PviewType() && Pinterface()
REPEAT G1(n, Pstatus) || G1(m, Pcontents) || Pcomment() || Pproperty()
    || PuserData()
ENDFORM PviewList IS FORM(KviewList)
REPEAT PviewRef() || PviewList()
ENDFORM PviewMap IS FORM(KviewMap)
REPEAT PportMap() || PportBackAnnotate() || PinstanceMap()
    || PinstanceBackAnnotate() || PnetMap() || PnetBackAnnotate()
    || Pcomment() || PuserData()
ENDFORM PviewNameDef IS ONCE PnameDef()
END PviewNameRef IS ONCE PnameRef()
END PviewRef IS FORM(KviewRef)
ONCE PviewNameRef()
OPTIONAL PcellRef()
ENDFORM PviewType IS FORM(KviewType)
ONCE MATCH(KBEHAVIOR) || MATCH(KDOCUMENT) || MATCH(KGRAPHIC)
    || MATCH(KLOGICMODEL) || MATCH(KMASKLAYOUT) || MATCH(KNETLIST)
    || MATCH(KPCBLAYOUT) || MATCH(KSCHEMATIC) || MATCH(KSTRANGER)
    || MATCH(KSYMBOLIC)
ENDFORM Pvisible IS FORM(Kvisible)
ONCE PbooleanValue()
ENDFORM PvoltageMap IS CONDFORM(KvoltageMap, LOGICMODEL)
ONCE PmiNoMaxValue()
ENDFORM PwaveValue IS CONDFORM(KwaveValue, LOGICMODEL)
ONCE PlogicNameDef() && PnumberValue() && PlogicWaveform()
ENDFORM Pweak IS CONDFORM(Kweak, LOGICMODEL)
ONCE PlogicNameRef()
ENDFORM PweakJoined IS FORM(KweakJoined)
REPEAT PportRef() || PportList() || Pjoined()
ENDFORM Pwhen IS CONDFORM(Kwhen, LOGICMODEL)
ONCE Ptrigger()
REPEAT Pafter() || Pfollow() || PlogicAssign() || Pmaintain() || Pcomment()
    || PuserData()
ENDFORM Pwhile IS FORM(Kwhile)
ONCE PbooleanValue()
REPEAT Pstatement()
ENDFORM Pwritten IS ZERO(l) ZERO(m) ZERO(n) FORM(Kwritten)
ONCE PtimeStamp()
REPEAT G1(l, Pauthor) || G1(m, Pprogram) || G1(n, PdataOrigin)
    || Pproperty() || Pcomment() || PuserData()
ENDFORM PxCoord IS FORM(KxCoord)
ONCE PpointValue()
ENDFORM Pxor IS FORM(Kxor)
REPEAT PbooleanValue()
ENDFORM PyCoord IS FORM(KyCoord)
ONCE PpointValue() ENDFORM
